-- 属性名登记表：唯一手写输入。
--
-- 新增属性：在对应域的列表末尾追加一行，然后运行 `xmake attribute-gen`。
-- 每个属性一个规范名，历史书写变体写进 alias（如 { name = "scroll_select", alias = { "scrollselect" } }）。
-- 别名在 IdOf() 中归一到规范名的 ID：链上每个属性只需一个 case。
-- 注意：共用一个处理分支但并非同一属性的名字（如布局的 columns/rows、富文本的 del/s/strike），
--       以及自身也是独立规范名的名字（如 Font/font），都应登记为独立条目，不要写成 alias。
-- 本文件是 AttributeIds.g.h / AttributeIds.g.cpp / CtrlDefs.g.h 的唯一数据来源。

function get_defs()
    return {
        ctrl = {
            { name = "Control", macro = "DUI_CTR_CONTROL" },
            { name = "ControlDragable", macro = "DUI_CTR_CONTROL_DRAGABLE" },
            { name = "ControlMovable", macro = "DUI_CTR_CONTROL_MOVABLE" },
            { name = "ControlResizable", macro = "DUI_CTR_CONTROL_RESIZABLE" },
            { name = "Label", macro = "DUI_CTR_LABEL" },
            { name = "RichText", macro = "DUI_CTR_RICHTEXT" },
            { name = "HyperLink", macro = "DUI_CTR_HYPER_LINK" },
            { name = "Button", macro = "DUI_CTR_BUTTON" },
            { name = "Option", macro = "DUI_CTR_OPTION" },
            { name = "CheckBox", macro = "DUI_CTR_CHECKBOX" },
            { name = "Split", macro = "DUI_CTR_SPLIT" },
            { name = "LabelBox", macro = "DUI_CTR_LABELBOX" },
            { name = "LabelHBox", macro = "DUI_CTR_LABELHBOX" },
            { name = "LabelVBox", macro = "DUI_CTR_LABELVBOX" },
            { name = "RichTextBox", macro = "DUI_CTR_RICHTEXT_BOX" },
            { name = "RichTextHBox", macro = "DUI_CTR_RICHTEXT_HBOX" },
            { name = "RichTextVBox", macro = "DUI_CTR_RICHTEXT_VBOX" },
            { name = "ButtonBox", macro = "DUI_CTR_BUTTONBOX" },
            { name = "ButtonHBox", macro = "DUI_CTR_BUTTONHBOX" },
            { name = "ButtonVBox", macro = "DUI_CTR_BUTTONVBOX" },
            { name = "CheckBoxBox", macro = "DUI_CTR_CHECKBOXBOX" },
            { name = "CheckBoxHBox", macro = "DUI_CTR_CHECKBOXHBOX" },
            { name = "CheckBoxVBox", macro = "DUI_CTR_CHECKBOXVBOX" },
            { name = "OptionBox", macro = "DUI_CTR_OPTIONBOX" },
            { name = "OptionHBox", macro = "DUI_CTR_OPTIONHBOX" },
            { name = "OptionVBox", macro = "DUI_CTR_OPTIONVBOX" },
            { name = "SplitBox", macro = "DUI_CTR_SPLITBOX" },
            { name = "Box", macro = "DUI_CTR_BOX" },
            { name = "HBox", macro = "DUI_CTR_HBOX" },
            { name = "VBox", macro = "DUI_CTR_VBOX" },
            { name = "HFlowBox", macro = "DUI_CTR_HFLOWBOX" },
            { name = "VFlowBox", macro = "DUI_CTR_VFLOWBOX" },
            { name = "XmlBox", macro = "DUI_CTR_XMLBOX" },
            { name = "VTileBox", macro = "DUI_CTR_VTILE_BOX" },
            { name = "HTileBox", macro = "DUI_CTR_HTILE_BOX" },
            { name = "BoxDragable", macro = "DUI_CTR_BOX_DRAGABLE" },
            { name = "HBoxDragable", macro = "DUI_CTR_HBOX_DRAGABLE" },
            { name = "VBoxDragable", macro = "DUI_CTR_VBOX_DRAGABLE" },
            { name = "BoxMovable", macro = "DUI_CTR_BOX_MOVABLE" },
            { name = "HBoxMovable", macro = "DUI_CTR_HBOX_MOVABLE" },
            { name = "VBoxMovable", macro = "DUI_CTR_VBOX_MOVABLE" },
            { name = "BoxResizable", macro = "DUI_CTR_BOX_RESIZABLE" },
            { name = "HBoxResizable", macro = "DUI_CTR_HBOX_RESIZABLE" },
            { name = "VBoxResizable", macro = "DUI_CTR_VBOX_RESIZABLE" },
            { name = "GroupBox", macro = "DUI_CTR_GROUP_BOX" },
            { name = "GroupHBox", macro = "DUI_CTR_GROUP_HBOX" },
            { name = "GroupVBox", macro = "DUI_CTR_GROUP_VBOX" },
            { name = "ScrollBox", macro = "DUI_CTR_SCROLLBOX" },
            { name = "HScrollBox", macro = "DUI_CTR_HSCROLLBOX" },
            { name = "VScrollBox", macro = "DUI_CTR_VSCROLLBOX" },
            { name = "HFlowScrollBox", macro = "DUI_CTR_HFLOW_SCROLLBOX" },
            { name = "VFlowScrollBox", macro = "DUI_CTR_VFLOW_SCROLLBOX" },
            { name = "HTileScrollBox", macro = "DUI_CTR_HTILE_SCROLLBOX" },
            { name = "VTileScrollBox", macro = "DUI_CTR_VTILE_SCROLLBOX" },
            { name = "ListBoxItem", macro = "DUI_CTR_LISTBOX_ITEM" },
            { name = "ListBoxItemH", macro = "DUI_CTR_LISTBOX_ITEM_HBOX" },
            { name = "ListBoxItemV", macro = "DUI_CTR_LISTBOX_ITEM_VBOX" },
            { name = "HListBox", macro = "DUI_CTR_HLISTBOX" },
            { name = "VListBox", macro = "DUI_CTR_VLISTBOX" },
            { name = "HTileListBox", macro = "DUI_CTR_HTILE_LISTBOX" },
            { name = "VTileListBox", macro = "DUI_CTR_VTILE_LISTBOX" },
            { name = "ListCtrl", macro = "DUI_CTR_LISTCTRL" },
            { name = "PropertyGrid", macro = "DUI_CTR_PROPERTY_GRID" },
            { name = "VirtualVListBox", macro = "DUI_CTR_VIRTUAL_VLISTBOX" },
            { name = "VirtualHListBox", macro = "DUI_CTR_VIRTUAL_HLISTBOX" },
            { name = "VirtualHTileListBox", macro = "DUI_CTR_VIRTUAL_HTILE_LISTBOX" },
            { name = "VirtualVTileListBox", macro = "DUI_CTR_VIRTUAL_VTILE_LISTBOX" },
            { name = "TabBox", macro = "DUI_CTR_TABBOX" },
            { name = "GridBox", macro = "DUI_CTR_GRIDBOX" },
            { name = "GridScrollBox", macro = "DUI_CTR_GRID_SCROLLBOX" },
            { name = "TreeNode", macro = "DUI_CTR_TREENODE" },
            { name = "TreeView", macro = "DUI_CTR_TREEVIEW" },
            { name = "DirectoryTree", macro = "DUI_CTR_DIRECTORY_TREE" },
            { name = "RichEdit", macro = "DUI_CTR_RICHEDIT" },
            { name = "RichEdit2", macro = "DUI_CTR_RICHEDIT2" },
            { name = "Combo", macro = "DUI_CTR_COMBO" },
            { name = "ComboButton", macro = "DUI_CTR_COMBO_BUTTON" },
            { name = "FilterCombo", macro = "DUI_CTR_FILTER_COMBO" },
            { name = "CheckCombo", macro = "DUI_CTR_CHECK_COMBO" },
            { name = "Slider", macro = "DUI_CTR_SLIDER" },
            { name = "Progress", macro = "DUI_CTR_PROGRESS" },
            { name = "CircleProgress", macro = "DUI_CTR_CIRCLEPROGRESS" },
            { name = "ScrollBar", macro = "DUI_CTR_SCROLLBAR" },
            { name = "Menu", macro = "DUI_CTR_MENU" },
            { name = "SubMenu", macro = "DUI_CTR_SUB_MENU" },
            { name = "MenuItem", macro = "DUI_CTR_MENU_ITEM" },
            { name = "MenuListBox", macro = "DUI_CTR_MENU_LISTBOX" },
            { name = "MenuBar", macro = "DUI_CTR_MENU_BAR" },
            { name = "MenuBarItem", macro = "DUI_CTR_MENU_BAR_ITEM" },
            { name = "DateTime", macro = "DUI_CTR_DATETIME" },
            -- 扩展控件类名（CefControl/WebView2Control 等）不进入核心表：
            -- 它们由扩展通过 AddCreateControlCallback 自注册，登记在 attribute_check.lua 的白名单中。
            { name = "ColorControl", macro = "DUI_CTR_COLOR_CONTROL" },
            { name = "ColorSlider", macro = "DUI_CTR_COLOR_SLIDER" },
            { name = "ColorPickerRegular", macro = "DUI_CTR_COLOR_PICKER_REGULAR" },
            { name = "ColorPickerStandard", macro = "DUI_CTR_COLOR_PICKER_STANDARD" },
            { name = "ColorPickerStandardGray", macro = "DUI_CTR_COLOR_PICKER_STANDARD_GRAY" },
            { name = "ColorPickerCustom", macro = "DUI_CTR_COLOR_PICKER_CUSTOM" },
            { name = "Line", macro = "DUI_CTR_LINE" },
            { name = "IPAddress", macro = "DUI_CTR_IPADDRESS" },
            { name = "HotKey", macro = "DUI_CTR_HOTKEY" },
            { name = "TabCtrl", macro = "DUI_CTR_TAB_CTRL" },
            { name = "TabCtrlItem", macro = "DUI_CTR_TAB_CTRL_ITEM" },
            { name = "AddressBar", macro = "DUI_CTR_ADDRESS_BAR" },
            { name = "IconControl", macro = "DUI_CTR_ICON_CONTROL" },
            { name = "BitmapControl", macro = "DUI_CTR_BITMAP_CONTROL" },
            { name = "ChildWindow", macro = "DUI_CTR_CHILD_WINDOW" },
            { name = "window_title_bar", macro = "DUI_CTR_WINDOW_TITLE_BAR" },
            { name = "btn_window_close", macro = "DUI_CTR_WINDOW_BUTTON_CLOSE" },
            { name = "btn_window_min", macro = "DUI_CTR_WINDOW_BUTTON_MIN" },
            { name = "btn_window_max", macro = "DUI_CTR_WINDOW_BUTTON_MAX" },
            { name = "btn_window_restore", macro = "DUI_CTR_WINDOW_BUTTON_RESTORE" },
            { name = "btn_window_fullscreen", macro = "DUI_CTR_WINDOW_BUTTON_FULLSCREEN" },
            { name = "btn_window_language", macro = "DUI_CTR_WINDOW_BUTTON_LANGUAGE" },
            { name = "btn_window_theme", macro = "DUI_CTR_WINDOW_BUTTON_THEME" },
        },
        control = {
            "multi_select",
            "paint_selected_colors",
            { name = "scroll_select", alias = { "scrollselect" } },
            "select_next_when_active_removed",
            "frame_selection",
            "frame_selection_color",
            "frame_selection_alpha",
            "frame_selection_border_size",
            "frame_selection_border_color",
            "select_none_when_click_blank",
            "select_like_list_ctrl",
            "vscrollbar",
            { name = "vscrollbar_style", alias = { "vscrollbarstyle" } },
            "vscrollbar_class",
            "hscrollbar",
            { name = "hscrollbar_style", alias = { "hscrollbarstyle" } },
            "hscrollbar_class",
            { name = "scrollbar_padding", alias = { "scrollbarpadding" } },
            { name = "vscroll_unit", alias = { "vscrollunit" } },
            { name = "hscroll_unit", alias = { "hscrollunit" } },
            { name = "scrollbar_float", alias = { "scrollbarfloat" } },
            { name = "vscrollbar_left", alias = { "vscrollbarleft" } },
            { name = "hold_end", alias = { "holdend" } },
            { name = "selected_id", alias = { "selectedid" } },
            { name = "fade_switch", alias = { "fadeswitch" } },
            "fade_switch_type",
            "fade_switch_frame_interval_ms",
            "fade_switch_total_ms",
            "fade_switch_easing_function",
            "xml_file_path",
            "res_path",
            "address_path",
            "path_tooltip",
            "return_update_ui",
            "esc_update_ui",
            "kill_focus_update_ui",
            "rich_edit_class",
            "rich_edit_clear_btn_class",
            "sub_path_hbox_class",
            "sub_path_button_class",
            "sub_path_root_class",
            "path_separator_class",
            "bitmap_halign",
            "bitmap_valign",
            "bitmap_alpha",
            "bitmap_dest",
            "bitmap_src",
            "bitmap_margin",
            "bitmap_adaptive_dest_rect",
            "bitmap_stretch",
            "bitmap_multi_thread",
            "bitmap_file",
            "dropbox",
            "dropbox_item_class",
            "selected_item_class",
            { name = "dropbox_size", alias = { "dropboxsize" } },
            { name = "popup_top", alias = { "popuptop" } },
            "height",
            "shadow_type",
            "child_window_margin",
            "circular",
            { name = "circle_width", alias = { "circlewidth" } },
            "indicator",
            "clockwise",
            "bgcolor",
            "fgcolor",
            { name = "gradient_color", alias = { "gradientcolor" } },
            "cursor_file",
            "color_type",
            "combo_type",
            "combo_tree_view_class",
            "combo_tree_node_class",
            "combo_icon_class",
            "combo_edit_class",
            "combo_button_class",
            "combo_box_class",
            "left_button_class",
            "left_button_top_label_class",
            "left_button_bottom_label_class",
            "left_button_top_label_text",
            "left_button_bottom_label_text",
            "left_button_top_label_bkcolor",
            "left_button_bottom_label_bkcolor",
            "right_button_class",
            "format",
            "edit_format",
            "spin_class",
            "small_icon_size",
            "large_icon_size",
            "show_hiden_files",
            "show_system_files",
            "default_text",
            "default_text_id",
            "ip",
            "text_align",
            { name = "end_ellipsis", alias = { "endellipsis" } },
            { name = "path_ellipsis", alias = { "pathellipsis" } },
            { name = "single_line", alias = { "singleline" } },
            { name = "multi_line", alias = { "multiline" } },
            "text",
            { name = "text_id", alias = { "textid" } },
            { name = "auto_tooltip", alias = { "autotooltip" } },
            "font",
            "text_color",
            { name = "normal_text_color", alias = { "normaltextcolor" } },
            "hovered_text_color",
            { name = "hot_text_color", alias = { "hottextcolor" } },
            "pressed_text_color",
            { name = "pushed_text_color", alias = { "pushedtextcolor" } },
            { name = "disabled_text_color", alias = { "disabledtextcolor" } },
            { name = "text_padding", alias = { "textpadding" } },
            "replace_newline",
            "spacing_mul",
            "spacing_add",
            "vertical_text",
            "word_spacing",
            "use_font_height",
            "ascii_rotate_90",
            "rich_text",
            "vertical",
            "line_color",
            "line_width",
            "dash_style",
            "header_class",
            "header_item_class",
            "header_split_box_class",
            "header_split_control_class",
            "enable_header_drag_order",
            "check_box_class",
            "data_item_class",
            "data_sub_item_class",
            "row_grid_line_width",
            "row_grid_line_color",
            "column_grid_line_width",
            "column_grid_line_color",
            "report_view_class",
            "header_height",
            "data_item_height",
            "show_header",
            "enable_column_width_auto",
            "auto_check_select",
            "show_header_checkbox",
            "show_data_item_checkbox",
            "type",
            "icon_view_class",
            "icon_view_item_class",
            "icon_view_item_image_class",
            "icon_view_item_label_class",
            "list_view_class",
            "list_view_item_class",
            "list_view_item_image_class",
            "list_view_item_label_class",
            "enable_item_edit",
            "list_ctrl_richedit_class",
            "icon_spacing",
            "sorted_up_image",
            "sorted_down_image",
            "show_icon_at_top",
            "horizontal_layout",
            "horizontal",
            "hor",
            "min",
            "max",
            "value",
            { name = "progress_image", alias = { "progressimage" } },
            "stretch_fore_image",
            { name = "is_stretch_fore", alias = { "isstretchfore" } },
            { name = "progress_color", alias = { "progresscolor" } },
            "marquee",
            { name = "marquee_width", alias = { "marqueewidth" } },
            { name = "marquee_step", alias = { "marqueestep" } },
            "reverse",
            "property_grid_xml",
            "group_class",
            "group_label_class",
            "property_class",
            "property_name_label_class",
            "property_value_label_class",
            "left_column_width",
            "property_font_normal",
            "property_font_modified",
            "readonly",
            "password",
            "show_password",
            "password_char",
            "flash_password_char",
            "number_only",
            "number",
            "max_number",
            "min_number",
            "number_format",
            { name = "caret_color", alias = { "caretcolor" } },
            { name = "prompt_mode", alias = { "promptmode" } },
            { name = "prompt_color", alias = { "promptcolor" } },
            { name = "prompt_text", alias = { "prompttext" } },
            "prompt_text_id",
            "prompt_textid",
            "prompttextid",
            { name = "focused_image", alias = { "focusedimage" } },
            { name = "want_tab", alias = { "wanttab" } },
            "want_return",
            { name = "want_return_msg", alias = { "wantreturnmsg" } },
            "want_ctrl_return",
            { name = "return_msg_want_ctrl", alias = { "returnmsgwantctrl" } },
            "limit_text",
            { name = "max_char", alias = { "maxchar" } },
            "limit_chars",
            "word_wrap",
            "no_caret_readonly",
            "default_context_menu",
            "clear_btn_class",
            "show_password_btn_class",
            "wheel_zoom",
            "hide_selection",
            "focused_bottom_border_size",
            "focus_bottom_border_size",
            "focused_bottom_border_color",
            "focus_bottom_border_color",
            "zoom",
            { name = "auto_vscroll", alias = { "autovscroll" } },
            { name = "auto_hscroll", alias = { "autohscroll" } },
            "rich",
            "auto_detect_url",
            "allow_beep",
            "save_selection",
            "select_all_on_focused",
            "select_all_on_focus",
            "selection_bkcolor",
            "inactive_selection_bkcolor",
            "current_row_bkcolor",
            "inactive_current_row_bkcolor",
            "row_spacing_mul",
            "row_spacing_add",
            "enable_drag_out",
            "default_link_font_color",
            "hovered_link_font_color",
            "hover_link_font_color",
            "pressed_link_font_color",
            "mouse_down_link_font_color",
            "link_font_underline",
            "replace_brace",
            "trim_policy",
            "step",
            { name = "thumb_normal_image", alias = { "thumbnormalimage" } },
            "thumb_hovered_image",
            { name = "thumb_hot_image", alias = { "thumbhotimage" } },
            "thumb_pressed_image",
            { name = "thumb_pushed_image", alias = { "thumbpushedimage" } },
            { name = "thumb_disabled_image", alias = { "thumbdisabledimage" } },
            { name = "thumb_size", alias = { "thumbsize" } },
            { name = "progress_bar_padding", alias = { "progressbarpadding" } },
            "tab_box_name",
            "drag_order",
            "selected_tab_item_outline_width",
            "selected_tab_item_outline_color",
            "tab_ctrl_bottom_line_height",
            "tab_ctrl_bottom_line_color",
            "tab_box_item_index",
            "title",
            "title_id",
            "icon",
            "icon_class",
            "title_class",
            "close_button_class",
            "line_class",
            "selected_round_corner",
            "hovered_round_corner",
            "hot_round_corner",
            "hovered_padding",
            "hot_padding",
            "auto_hide_close_button",
            "expand_normal_image",
            "expand_hovered_image",
            "expand_hot_image",
            "expand_pressed_image",
            "expand_pushed_image",
            "expand_disabled_image",
            "collapse_normal_image",
            "collapse_hovered_image",
            "collapse_hot_image",
            "collapse_pressed_image",
            "collapse_pushed_image",
            "collapse_disabled_image",
            "expand_image_right_space",
            "check_box_image_right_space",
            "icon_image_right_space",
            "indent",
            "expand_image_class",
            "show_icon",
            { name = "mouse_child", alias = { "mousechild" } },
            "drag_out_id",
            "drop_in_id",
            "class",
            "enable_vars",
            "halign",
            "valign",
            "align",
            "margin",
            "padding",
            "control_padding",
            "bkcolor",
            "bkcolor2",
            "bkcolor2_direction",
            "fore_color",
            { name = "border_size", alias = { "bordersize" } },
            "border_dash_style",
            "borders_on_top",
            { name = "border_round", alias = { "borderround" } },
            { name = "box_shadow", alias = { "boxshadow" } },
            "width",
            "state",
            { name = "cursor_type", alias = { "cursortype" } },
            { name = "render_offset", alias = { "renderoffset" } },
            { name = "normal_color", alias = { "normalcolor" } },
            "hovered_color",
            { name = "hot_color", alias = { "hotcolor" } },
            "pressed_color",
            { name = "pushed_color", alias = { "pushedcolor" } },
            { name = "disabled_color", alias = { "disabledcolor" } },
            "normal_color_margin",
            "hovered_color_margin",
            "hot_color_margin",
            "pressed_color_margin",
            "pushed_color_margin",
            "disabled_color_margin",
            "state_color_min_width",
            "state_color_min_height",
            "normal_color_round",
            "hovered_color_round",
            "hot_color_round",
            "pressed_color_round",
            "pushed_color_round",
            "disabled_color_round",
            { name = "border_color", alias = { "bordercolor" } },
            "normal_border_color",
            "hovered_border_color",
            "hot_border_color",
            "pressed_border_color",
            "pushed_border_color",
            "disabled_border_color",
            "focused_border_color",
            "focus_border_color",
            { name = "left_border_size", alias = { "leftbordersize" } },
            { name = "top_border_size", alias = { "topbordersize" } },
            { name = "right_border_size", alias = { "rightbordersize" } },
            { name = "bottom_border_size", alias = { "bottombordersize" } },
            "bkimage",
            { name = "min_width", alias = { "minwidth" } },
            { name = "max_width", alias = { "maxwidth" } },
            { name = "min_height", alias = { "minheight" } },
            { name = "max_height", alias = { "maxheight" } },
            "name",
            { name = "tooltip_text", alias = { "tooltiptext" } },
            "tooltip_text_id",
            "tooltip_textid",
            "tooltiptextid",
            "tooltip_width",
            { name = "data_id", alias = { "dataid" } },
            "user_data_id",
            "user_dataid",
            "enabled",
            "mouse_enabled",
            "mouse",
            "keyboard_enabled",
            "keyboard",
            "visible",
            { name = "fade_visible", alias = { "fadevisible" } },
            "float",
            "keep_float_pos",
            "cache",
            { name = "no_focus", alias = { "nofocus" } },
            "alpha",
            { name = "normal_image", alias = { "normalimage" } },
            "hovered_image",
            { name = "hot_image", alias = { "hotimage" } },
            "pressed_image",
            { name = "pushed_image", alias = { "pushedimage" } },
            { name = "disabled_image", alias = { "disabledimage" } },
            { name = "fore_normal_image", alias = { "forenormalimage" } },
            "fore_hovered_image",
            { name = "fore_hot_image", alias = { "forehotimage" } },
            "fore_pressed_image",
            { name = "fore_pushed_image", alias = { "forepushedimage" } },
            { name = "fore_disabled_image", alias = { "foredisabledimage" } },
            { name = "fade_alpha", alias = { "fadealpha" } },
            "fade_hovered",
            { name = "fade_hot", alias = { "fadehot" } },
            "fade_hovered_frame_interval_ms",
            "fade_hot_frame_interval_ms",
            "fade_hovered_total_ms",
            "fade_hot_total_ms",
            "fade_hovered_easing_function",
            "fade_hot_easing_function",
            { name = "fade_width", alias = { "fadewidth" } },
            { name = "fade_height", alias = { "fadeheight" } },
            "fade_size",
            { name = "fade_in_out_x_from_left", alias = { "fadeinoutxfromleft" } },
            { name = "fade_in_out_x_from_right", alias = { "fadeinoutxfromright" } },
            { name = "fade_in_out_y_from_top", alias = { "fadeinoutyfromtop" } },
            { name = "fade_in_out_y_from_bottom", alias = { "fadeinoutyfrombottom" } },
            "fade_frame_interval_ms",
            "fade_total_ms",
            "fade_easing_function",
            { name = "tab_stop", alias = { "tabstop" } },
            "loading",
            "show_focused_rect",
            "show_focus_rect",
            "focused_rect_color",
            "focus_rect_color",
            "paint_order",
            "start_image_animation",
            "start_gif_play",
            "stop_image_animation",
            "stop_gif_play",
            "set_image_animation_frame",
            "enable_drag_drop",
            "enable_drop_file",
            "drop_file_types",
            "row_span",
            "col_span",
            { name = "button1_normal_image", alias = { "button1normalimage" } },
            "button1_hovered_image",
            { name = "button1_hot_image", alias = { "button1hotimage" } },
            "button1_pressed_image",
            { name = "button1_pushed_image", alias = { "button1pushedimage" } },
            { name = "button1_disabled_image", alias = { "button1disabledimage" } },
            { name = "button2_normal_image", alias = { "button2normalimage" } },
            "button2_hovered_image",
            { name = "button2_hot_image", alias = { "button2hotimage" } },
            "button2_pressed_image",
            { name = "button2_pushed_image", alias = { "button2pushedimage" } },
            { name = "button2_disabled_image", alias = { "button2disabledimage" } },
            { name = "rail_normal_image", alias = { "railnormalimage" } },
            "rail_hovered_image",
            { name = "rail_hot_image", alias = { "railhotimage" } },
            "rail_pressed_image",
            { name = "rail_pushed_image", alias = { "railpushedimage" } },
            { name = "rail_disabled_image", alias = { "raildisabledimage" } },
            { name = "bk_normal_image", alias = { "bknormalimage" } },
            "bk_hovered_image",
            { name = "bk_hot_image", alias = { "bkhotimage" } },
            "bk_pressed_image",
            { name = "bk_pushed_image", alias = { "bkpushedimage" } },
            { name = "bk_disabled_image", alias = { "bkdisabledimage" } },
            { name = "line_size", alias = { "linesize" } },
            { name = "thumb_min_length", alias = { "thumbminlength" } },
            "range",
            { name = "show_button1", alias = { "showbutton1" } },
            { name = "show_button2", alias = { "showbutton2" } },
            { name = "auto_hide_scroll", alias = { "autohidescroll" } },
            "selected",
            { name = "switch_select", alias = { "switchselect" } },
            "support_check_Mode",
            "auto_select_check",
            { name = "normal_first", alias = { "normalfirst" } },
            { name = "selected_normal_image", alias = { "selectednormalimage" } },
            "selected_hovered_image",
            { name = "selected_hot_image", alias = { "selectedhotimage" } },
            "selected_pressed_image",
            { name = "selected_pushed_image", alias = { "selectedpushedimage" } },
            { name = "selected_disabled_image", alias = { "selecteddisabledimage" } },
            { name = "selected_fore_normal_image", alias = { "selectedforenormalimage" } },
            "selected_fore_hovered_image",
            { name = "selected_fore_hot_image", alias = { "selectedforehotimage" } },
            "selected_fore_pressed_image",
            { name = "selected_fore_pushed_image", alias = { "selectedforepushedimage" } },
            { name = "selected_fore_disabled_image", alias = { "selectedforedisabledimage" } },
            "part_selected_normal_image",
            "part_selected_hovered_image",
            "part_selected_hot_image",
            "part_selected_pressed_image",
            "part_selected_pushed_image",
            "part_selected_disabled_image",
            "part_selected_fore_normal_image",
            "part_selected_fore_hovered_image",
            "part_selected_fore_hot_image",
            "part_selected_fore_pressed_image",
            "part_selected_fore_pushed_image",
            "part_selected_fore_disabled_image",
            { name = "selected_text_color", alias = { "selectedtextcolor" } },
            { name = "selected_normal_text_color", alias = { "selectednormaltextcolor" } },
            "selected_hovered_text_color",
            { name = "selected_hot_text_color", alias = { "selectedhottextcolor" } },
            "selected_pressed_text_color",
            { name = "selected_pushed_text_color", alias = { "selectedpushedtextcolor" } },
            { name = "selected_disabled_text_color", alias = { "selecteddisabledtextcolor" } },
            { name = "selected_normal_color", alias = { "selectednormalcolor" } },
            "selected_hovered_color",
            { name = "selected_hot_color", alias = { "selectedhotcolor" } },
            "selected_pressed_color",
            { name = "selected_pushed_color", alias = { "selectedpushedcolor" } },
            { name = "selected_disabled_color", alias = { "selecteddisabledcolor" } },
            "selected_normal_color_margin",
            "selected_hovered_color_margin",
            "selected_hot_color_margin",
            "selected_pressed_color_margin",
            "selected_pushed_color_margin",
            "selected_disabled_color_margin",
            "selected_normal_color_round",
            "selected_hovered_color_round",
            "selected_hot_color_round",
            "selected_pressed_color_round",
            "selected_pushed_color_round",
            "selected_disabled_color_round",
            "corner_size",
            "url",
            "show_url_tooltip",
            "group",
            "enable_split_single",
            "drag_alpha",
            "drag_out",
            "enable_move_pos",
            "move_parent_pos",
            "move_pos_alpha",
            "move_pos_non_draggable_margin",
            "move_pos_draggable_border",
            "move_pos_reserve_width",
            "move_pos_reserve_height",
            "move_pos_keep_within_parent",
            "enable_resize",
            "resize_size_box",
            "resize_reserve_width",
            "resize_reserve_height",
            "resize_keep_within_parent",
            "url_is_local_file",
            "F12",
            "F11",
            "download_favicon_image",
            "devtools_enabled",
            "rows",
            "columns",
            "grid_width",
            "grid_height",
            { name = "scale_down", alias = { "scaledown" } },
            { name = "item_size", alias = { "itemsize" } },
            "auto_calc_item_size",
            { name = "child_margin", alias = { "childmargin" } },
            { name = "child_margin_x", alias = { "childmarginx" } },
            { name = "child_margin_y", alias = { "childmarginy" } },
            "child_valign",
            "child_halign",
            "child_align",
        },
        window = {
            "use_system_caption",
            { name = "shadow_attached", alias = { "shadowattached" } },
            "shadow_type",
            { name = "layered_window", alias = { "layeredwindow" } },
            "alpha",
            "layered_window_alpha",
            "opacity",
            "layered_window_opacity",
            "drag_drop",
            "render_backend_type",
            { name = "size_box", alias = { "sizebox" } },
            "caption",
            { name = "shadow_corner", alias = { "shadowcorner" } },
            "size",
            "size_contain_shadow",
            "min_size",
            "mininfo",
            "max_size",
            "maxinfo",
            "sdl_render_name",
            "snap_layout_menu",
            "sys_menu",
            "sys_menu_rect",
            "icon",
            "text",
            { name = "text_id", alias = { "textid" } },
            { name = "round_corner", alias = { "roundcorner" } },
            { name = "shadow_image", alias = { "shadowimage" } },
            "shadow_border_round",
            "shadow_border_size",
            "shadow_border_color",
            "shadow_snap",
            "name",
            "value",
            "file",
            "desc",
            "id",
            "bold",
            "underline",
            "strikeout",
            "italic",
            "default",
            "type",
            "receiver",
            { name = "apply_attribute", alias = { "applyattribute" } },
        },
        node = {
            "Window",
            "Global",
            "Class",
            "ThemeColor",
            "TextColor",
            "Font",
            "DefaultFontFamilyNames",
            "FallbackFontFamilyNames",
            "FontFile",
            "Alias",
            "Var",
            "Theme",
            "FontResource",
            "ThemeMeta",
            "Include",
            "PropertyGridGroup",
            "CheckComboText",
            "ListCtrlHeaderItem",
            "ListCtrlItem",
            "ListCtrlSubItem",
            "Event",
            "BubbledEvent",
            "PropertyGridTextProperty",
            "PropertyGridComboProperty",
            "PropertyGridFontProperty",
            "PropertyGridFontSizeProperty",
            "PropertyGridColorProperty",
            "PropertyGridDateTimeProperty",
            "PropertyGridIPAddressProperty",
            "PropertyGridHotKeyProperty",
            "PropertyGridFileProperty",
            "PropertyGridDirectoryProperty",
            "a",
            "b",
            "i",
            "del",
            "s",
            "strike",
            "ins",
            "u",
            "bgcolor",
            "font",
            "br",
        },
        image = {
            "file",
            "res",
            "name",
            "width",
            "height",
            "src",
            "source",
            "corner",
            "window_shadow_mode",
            { name = "dpi_scale", alias = { "dpiscale" } },
            { name = "dest_scale", alias = { "destscale" } },
            "dest",
            "margin",
            "padding",
            "halign",
            "valign",
            "fade",
            "alpha",
            "xtiled",
            { name = "full_xtiled", alias = { "fullxtiled" } },
            "ytiled",
            { name = "full_ytiled", alias = { "fullytiled" } },
            { name = "tiled_margin", alias = { "tiledmargin" } },
            "tiled_margin_x",
            "tiled_margin_y",
            "tiled_padding",
            { name = "icon_size", alias = { "iconsize" } },
            "icon_as_animation",
            "icon_frame_delay",
            "pag_max_frame_rate",
            { name = "play_count", alias = { "playcount" } },
            "auto_play",
            "async_load",
            "adaptive_dest_rect",
            "svg_replace_colors",
            "assert",
        },
        shadow = {
            "big",
            "big_round",
            "small",
            "small_round",
            "menu",
            "menu_round",
            "none",
            "none_round",
            "custom",
            "default",
            "system_default",
            "system_not_round",
            "system_round",
            "system_small_round",
        },
        loading = {
            "file",
            "width",
            "height",
            "offset_x",
            "offset_y",
            "halign",
            "valign",
            "fade",
            "auto_stop",
            "animation_control",
        },
    }
end
